"""database restructure for save files

Revision ID: dd9fd335ec8b
Revises: 
Create Date: 2023-11-18 16:09:55.071571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9fd335ec8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_fk', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('datetime_created', sa.String(), nullable=True),
    sa.Column('datetime_last_played', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_fk'], ['users.id'], name=op.f('fk_characters_user_fk_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_fk', sa.Integer(), nullable=True),
    sa.Column('achievement_fk', sa.Integer(), nullable=True),
    sa.Column('datetime_achieved', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_fk'], ['achievements.id'], name=op.f('fk_users_achievements_achievement_fk_achievements')),
    sa.ForeignKeyConstraint(['user_fk'], ['users.id'], name=op.f('fk_users_achievements_user_fk_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('save_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_fk', sa.Integer(), nullable=True),
    sa.Column('datetime_created', sa.String(), nullable=True),
    sa.Column('location_on_save', sa.String(), nullable=True),
    sa.Column('has_entered_portal', sa.String(), nullable=True),
    sa.Column('has_map', sa.String(), nullable=True),
    sa.Column('met_girl', sa.String(), nullable=True),
    sa.Column('girls_item_location', sa.String(), nullable=True),
    sa.Column('found_girls_item', sa.String(), nullable=True),
    sa.Column('has_visited_store', sa.String(), nullable=True),
    sa.Column('gold_pieces', sa.Integer(), nullable=True),
    sa.Column('has_seeking_spell', sa.String(), nullable=True),
    sa.Column('mini_game_high_score', sa.Integer(), nullable=True),
    sa.Column('met_village2_trader', sa.String(), nullable=True),
    sa.Column('accepted_quest_village2_trader', sa.String(), nullable=True),
    sa.Column('met_village1_trade_target', sa.String(), nullable=True),
    sa.Column('negotiated_deal', sa.String(), nullable=True),
    sa.Column('wizard_is_home', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['character_fk'], ['characters.id'], name=op.f('fk_save_files_character_fk_characters')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('save_files')
    op.drop_table('users_achievements')
    op.drop_table('characters')
    op.drop_table('users')
    op.drop_table('achievements')
    # ### end Alembic commands ###
