"""empty message

Revision ID: f46864a415f4
Revises: 
Create Date: 2023-11-14 15:21:45.426390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46864a415f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('save_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('user_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_fk'], ['users.id'], name=op.f('fk_save_files_user_fk_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_fk', sa.Integer(), nullable=True),
    sa.Column('achievement_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_fk'], ['achievements.id'], name=op.f('fk_users_achievements_achievement_fk_achievements')),
    sa.ForeignKeyConstraint(['user_fk'], ['users.id'], name=op.f('fk_users_achievements_user_fk_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_achievements')
    op.drop_table('save_files')
    op.drop_table('users')
    op.drop_table('achievements')
    # ### end Alembic commands ###
